### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by BlackJoker90** [Naam/paperless-alfred#2]
Hi,

how can I install the workflow? I downloaded the the zip but it doesn't contain a alfred workflow file.

**Comment by Naam** [comment]
Alfred workflows are just `.zip` named `.alfredworkflow`. You can simply rename it for now; sorry for the confusion.
I will add this bit to the documentation in `README.md`. GitHub won't take the `.alfredworkflow` as release format if I recall correctly, the right solution is to have the `.alfredworkflow` in the `.zip`, but it felt redundant to me at the time. I can see how this is confusing, though. So, for the next release, I'll do just that.

Hope this helps, let me know if I can close the issue

**Comment by BlackJoker90** [comment]
That worked the things out thank you very much 👍
